import type { Metadata } from "next";
import localFont from "next/font/local";
import "../globals.css";
import { ThemeProvider } from "@/components/theme-provider";
// import MobileNav from "./(root)/_components/MobileNav";
// import AppSidebar from "./(root)/_components/AppSidebar";
import { SidebarProvider } from "@/components/ui/sidebar";
import AppSidebar from "./_components/AppSidebar";
import MobileNav from "./_components/MobileNav";
// import MobileNav from "./_components/MobileNav";

const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        // bg-zinc-950 dark:bg-white
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#18181b] `}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="w-full h-auto flex items-start  lg:gap-x-32 md:gap-x-16 sm:gap-x-8 gap-x-4 relative">
            <div className=" sm:w-none w-none h-[100vh] pt-10 px-3  border-r-gray-500 sticky top-0 left-0 lg:block md:block sm:hidden hidden">
              <SidebarProvider
                style={
                  {
                    "--sidebar-width": "350px",
                  } as React.CSSProperties
                }
              >
                <AppSidebar />
              </SidebarProvider>
            </div>

            {/* Cotton Navbar small screen */}
            <div className="w-full h-auto py-1 px-3 border-t border-t-[#1d1d1d] fixed bottom-0 left-0 lg:hidden md:hidden sm:block block bg-black z-50">
              <MobileNav />
            </div>

            {children}
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
